code --install-extension Extensions installed on WSL: Ubuntu: --force &
code --install-extension aaron-bond.better-comments --force &
code --install-extension adrianwilczynski.add-reference --force &
code --install-extension adrianwilczynski.asp-net-core-switcher --force &
code --install-extension adrianwilczynski.blazor-snippet-pack --force &
code --install-extension adrianwilczynski.csharp-to-typescript --force &
code --install-extension adrianwilczynski.libman --force &
code --install-extension adrianwilczynski.namespace --force &
code --install-extension adrianwilczynski.terminal-commands --force &
code --install-extension adrianwilczynski.toggle-hidden --force &
code --install-extension adrianwilczynski.user-secrets --force &
code --install-extension amazonwebservices.aws-toolkit-vscode --force &
code --install-extension aws-scripting-guy.cform --force &
code --install-extension batisteo.vscode-django --force &
code --install-extension Boto3typed.boto3-ide --force &
code --install-extension christian-kohler.path-intellisense --force &
code --install-extension codezombiech.gitignore --force &
code --install-extension dbaeumer.vscode-eslint --force &
code --install-extension doggy8088.netcore-extension-pack --force &
code --install-extension doggy8088.netcore-snippets --force &
code --install-extension doggy8088.quicktype-refresh --force &
code --install-extension donjayamanne.python-environment-manager --force &
code --install-extension donjayamanne.python-extension-pack --force &
code --install-extension eamodio.gitlens --force &
code --install-extension EditorConfig.EditorConfig --force &
code --install-extension esbenp.prettier-vscode --force &
code --install-extension fknop.vscode-npm --force &
code --install-extension formulahendry.dotnet --force &
code --install-extension formulahendry.dotnet-test-explorer --force &
code --install-extension foxundermoon.shell-format --force &
code --install-extension ivory-lab.jenkinsfile-support --force &
code --install-extension janjoerke.jenkins-pipeline-linter-connector --force &
code --install-extension jmrog.vscode-nuget-package-manager --force &
code --install-extension josephwoodward.vscodeilviewer --force &
code --install-extension k--kato.docomment --force &
code --install-extension kddejong.vscode-cfn-lint --force &
code --install-extension KevinRose.vsc-python-indent --force &
code --install-extension kiteco.kite --force &
code --install-extension kreativ-software.csharpextensions --force &
code --install-extension lizebang.bash-extension-pack --force &
code --install-extension Maarti.jenkins-doc --force &
code --install-extension mads-hartmann.bash-ide-vscode --force &
code --install-extension magicstack.MagicPython --force &
code --install-extension mgesbert.indent-nested-dictionary --force &
code --install-extension mhutchie.git-graph --force &
code --install-extension ms-azure-devops.azure-pipelines --force &
code --install-extension ms-azuretools.vscode-docker --force &
code --install-extension ms-dotnettools.csharp --force &
code --install-extension ms-dotnettools.vscode-dotnet-runtime --force &
code --install-extension ms-ossdata.vscode-postgresql --force &
code --install-extension ms-python.python --force &
code --install-extension ms-python.vscode-pylance --force &
code --install-extension ms-toolsai.jupyter --force &
code --install-extension ms-vscode.azure-account --force &
code --install-extension ms-vscode.powershell --force &
code --install-extension ms-vscode.vscode-typescript-tslint-plugin --force &
code --install-extension NicolasVuillamy.vscode-groovy-lint --force &
code --install-extension njpwerner.autodocstring --force &
code --install-extension njqdev.vscode-python-typehint --force &
code --install-extension p1c2u.jenkins --force &
code --install-extension patcx.vscode-nuget-gallery --force &
code --install-extension pflannery.vscode-versionlens --force &
code --install-extension recode4dev.jenkinsfile --force &
code --install-extension redhat.fabric8-analytics --force &
code --install-extension redhat.vscode-yaml --force &
code --install-extension Remisa.shellman --force &
code --install-extension rogalmic.bash-debug --force &
code --install-extension rpinski.shebang-snippets --force &
code --install-extension shakram02.bash-beautify --force &
code --install-extension SonarSource.sonarlint-vscode --force &
code --install-extension TabNine.tabnine-vscode --force &
code --install-extension ThreadHeap.serverless-ide-vscode --force &
code --install-extension tht13.python --force &
code --install-extension timonwong.shellcheck --force &
code --install-extension tintoy.msbuild-project-tools --force &
code --install-extension VisualStudioExptTeam.intellicode-api-usage-examples --force &
code --install-extension VisualStudioExptTeam.vscodeintellicode --force &
code --install-extension VisualStudioExptTeam.vscodeintellicode-insiders --force &
code --install-extension wayou.vscode-todo-highlight --force &
code --install-extension wholroyd.jinja --force &
code --install-extension yzhang.markdown-all-in-one --force &
code --install-extension zxh404.vscode-proto3 --force
